export const PERSISTENCE_CACHE_METADATA_TTL = 'PERSISTENCE_CACHE_TTL';
export const PERSISTENCE_CACHE_METADATA_KEY = 'PERSISTENCE_CACHE_KEY';

export const PERSISTENCE_CACHE_KEY_GRAPH = 'graph-data';
export const PERSISTENCE_CACHE_KEY_CONFIG = 'collection-config';
